name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Clickable
        run: |
          sudo apt install adb git python3 python3-pip python3-setuptools
          pip3 install --user clickable-ut --upgrade
          echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc

      - uses: actions/setup-node@v2
        with:
           node-version: '17.x'
           
      - name: Install dependencies
        run: cd yt-ws; npm install; cd ..
        
      - name: Download Node
        run: |
          clickable build --libs --arch amd64;
          clickable build --libs --arch armhf;
          clickable build --libs --arch arm64;

      - name: Build the app
          clickable build --arch amd64;
          clickable build --arch armhf;
          clickable build --arch arm64;

      - uses: actions/upload-artifact@v3
        with:
          name: Builds
          path: build/*/app/*.click
